name: PoEM Core Build

on:
  push:
    branches: [ "main", "master", "dev", "develop", "release/*", "fix-build" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with debugging enabled'
        type: boolean
        required: false
        default: false

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up GCC 9
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 9
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          g++-9 \
          gcc-9 \
          libtool \
          autotools-dev \
          automake \
          pkg-config \
          libssl-dev \
          libevent-dev \
          bsdmainutils \
          libboost-system-dev \
          libboost-filesystem-dev \
          libboost-chrono-dev \
          libboost-program-options-dev \
          libboost-test-dev \
          libboost-thread-dev \
          libboost-signals-dev \
          git \
          wget \
          ca-certificates
          
        # Set GCC 9 as default
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-9 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-9
        sudo update-alternatives --set gcc /usr/bin/gcc-9
        
        # Verify compiler versions
        gcc --version
        g++ --version
    
    - name: Build
      run: |
        # Set compiler flags for maximum compatibility
        export CXX="g++-9"
        export CC="gcc-9"
        export CXXFLAGS="-O2 -pipe -std=c++11 -fPIC"
        export CFLAGS="-O2 -pipe -fPIC"
        export CPPFLAGS=""
        export LDFLAGS="-Wl,-O1 -Wl,--as-needed"
        
        # Set Boost flags
        export BOOST_ROOT="/usr"
        
        ./autogen.sh
        ./configure \
          --prefix=${{ github.workspace }}/depends/x86_64-linux-gnu \
          --disable-tests \
          --disable-bench \
          --without-gui \
          --disable-wallet \
          --disable-zmq \
          --disable-man \
          CXXFLAGS="$CXXFLAGS" \
          CFLAGS="$CFLAGS" \
          CPPFLAGS="$CPPFLAGS"
        make -j$(nproc) V=1
    
    - name: Check Binary
      run: |
        file src/poemd
        ls -la src/poemd
    
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: poem-linux-binaries
        path: src/poemd
        if-no-files-found: error
        retention-days: 5
