name: PoEM Core Build

on:
  push:
    branches: [ "main", "master", "dev", "develop", "release/*", "fix-build" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with debugging enabled'
        type: boolean
        required: false
        default: false

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libtool \
          autotools-dev \
          automake \
          pkg-config \
          libssl-dev \
          libevent-dev \
          bsdmainutils \
          libboost-system-dev \
          libboost-filesystem-dev \
          libboost-chrono-dev \
          libboost-program-options-dev \
          libboost-test-dev \
          libboost-thread-dev \
          git
    
    - name: Build
      run: |
        export CXXFLAGS="-O2 -pipe -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0"
        export CFLAGS="-O2 -pipe"
        export CPPFLAGS=""
        
        ./autogen.sh
        ./configure \
          --prefix=${{ github.workspace }}/depends/x86_64-linux-gnu \
          --disable-tests \
          --disable-bench \
          --without-gui \
          --disable-wallet \
          --disable-zmq \
          --disable-man \
          CXXFLAGS="$CXXFLAGS" \
          CFLAGS="$CFLAGS" \
          CPPFLAGS="$CPPFLAGS"
        make -j$(nproc) V=1
    
    - name: Check Binary
      run: |
        file src/poemd
        ls -la src/poemd
    
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: poem-linux-binaries
        path: src/poemd
        if-no-files-found: error
        retention-days: 5
