name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool pkg-config build-essential \
            libevent-dev libssl-dev libminiupnpc-dev \
            libboost-all-dev

      - name: Fetch submodules (if any)
        run: git submodule update --init --recursive

      - name: Clean previous build artifacts
        run: |
          make distclean || true

      - name: Generate build system
        run: |
          if [ -f autogen.sh ]; then
            ./autogen.sh
          fi

      - name: Configure project
        run: |
          ./configure \
            --enable-static \
            --with-pic \
            --with-incompatible-bdb \
            --with-qt=no \
            --disable-tests \
            --disable-bench \
            --disable-wallet \
            --disable-zmq \
            CPPFLAGS="-DHAVE_CONFIG_H"

      - name: Build project
        run: |
          make -j$(nproc)

          # Check for built binaries
          find src/ -type f -executable -ls

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: poem-binaries
          path: |
            src/poemd
            src/poem-cli
            src/poem-tx
            src/dogecoind
            src/dogecoin-cli
            src/dogecoin-tx
