name: CI Build on rename2

on:
  push:
    branches:
      - rename2
  pull_request:
    branches:
      - rename2

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
        sudo apt-get install -y libssl-dev libevent-dev libboost-system1.74-dev libboost-filesystem1.74-dev \
          libboost-chrono1.74-dev libboost-test1.74-dev libboost-thread1.74-dev libboost-program-options1.74-dev \
          libminiupnpc-dev libzmq3-dev libqt5gui5 libqt5core5a libqt5dbus5 \
          qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev \
          libdb++-dev libdb-dev unzip

    - name: Build
      run: |
        ./autogen.sh
        export BOOST_LDFLAGS="-L/usr/lib/x86_64-linux-gnu"
        export BOOST_CPPFLAGS="-I/usr/include/boost"
        ./configure --disable-wallet --without-gui --disable-tests --disable-bench \
                   --with-boost-libdir=/usr/lib/x86_64-linux-gnu \
                   --with-boost=/usr \
                   CXXFLAGS="-g -O2 -std=c++17"
        make -j$(nproc) V=1

    - name: Run basic tests
      run: |
        ./src/test/test_dogecoin
        ./src/bench/bench_dogecoin --list | head -n 5

    - name: Verify binaries
      run: |
        file src/dogecoind
        file src/dogecoin-cli
        ./src/dogecoind --version
        ./src/dogecoin-cli --version
